server:
  port: 10004

spring:
  datasource:

    url: jdbc:h2:mem:csv2sql
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  jpa:
    hibernate:
    ddl-auto: update
